export const PROJECTS = [
  {
    id: 1,
    title: "My portfolio",
    description: "",
    clone: "",
    repo: "",
    languages: [
      { id: 1, label: "JavaScript", per: 60 },
      { id: 2, label: "CSS", per: 30 },
      { id: 3, label: "HTML", per: 10 },
    ],
    github: "",
    updatedAt: "Jan 17, 2024",
  },
  {
    id: 2,
    title: "Create react app lambda",
    description: "",
    clone: "",
    repo: "",
    languages: [],
    github: "",
    updatedAt: "Dec 7, 2023",
  },
  {
    id: 3,
    title: "Task management",
    description:
      "It is a task mangement system where all user track their own tasks with the status of in-progress, pending, and completed",
    clone: "",
    repo: "",
    languages: [
      { id: 1, label: "JavaScript", per: 78 },
      { id: 2, label: "CSS", per: 22 },
      { id: 3, label: "HTML", per: 10 },
    ],
    github: "",
    updatedAt: "Feb 5, 2023",
  },
  {
    id: 4,
    title: "Vikas Kumar",
    description: "Config files form my github profile.",
    clone: "",
    repo: "",
    languages: [],
    github: "",
    updatedAt: "Oct 27, 2021",
  },
];
